const apiAddressHead =
  process.env.NODE_ENV === 'development' ? '/api' : process.env.REACT_APP_BASE_URL;

export const API = {
  SHARE_LIST: `${apiAddressHead}/shares`,
  SHARES_WRITER: `${apiAddressHead}/shares/writer`,
  SHARE_RECOMMENDED: `${apiAddressHead}/shares/recommendation`,
  SHARE_MINE: `${apiAddressHead}/shares/mine`,
  CHATROOMS: `${apiAddressHead}/chatrooms`,
  CHATROOM_MEMBERS: `${apiAddressHead}/chatroom-members`,
  CHATS_UNREAD: `${apiAddressHead}/chats/unread`,
  CHATROOM_IDS: `${apiAddressHead}/chatroom-members`,
  CHAT_UPDATE_READ_TIME: `${apiAddressHead}/chat-logs/update-read-time`,
  SOCKET: `${apiAddressHead}/socket`,
  LOGIN_FORM: '/login/form',
  LOGIN_VERIFICATION: `${apiAddressHead}/login/verification`,
  LOGIN: `${apiAddressHead}/login`,
  LOGOUT: `${apiAddressHead}/logout`,
  ENTRIES: `${apiAddressHead}/entries`,
  CHECK_LOGIN: `${apiAddressHead}/reissue/access-token`,
  WISH_LIST: `${apiAddressHead}/wish-list`,
  MY_SHARE: `${apiAddressHead}/shares/mine`,
  MEMBERS: `${apiAddressHead}/members`,
  KEYWORD: `${apiAddressHead}/keywords`,
  WEBSOCKET: `${apiAddressHead}/websocket`,
  REGISTERED_KEYWORD: `${apiAddressHead}/keywords/location`,
  DELETE_REGISTERED_KEYWORD: (id: number) => `${apiAddressHead}/keywords/${id}`,
  NOTICE: `${apiAddressHead}/notifications`,
  NOTICE_ACTIVITY: `${apiAddressHead}/notifications/activity`,
  NOTICE_KEYWORD: `${apiAddressHead}/notifications/keyword`,
  DELETE_WISH_LIST: `${apiAddressHead}/wish-list`,
  DELETE_HISTORY_LIST: (id: number) => `${apiAddressHead}/shares/${id}/entry`,
  DELETE_SALES: (id: number) => `${apiAddressHead}/shares/${id}`,
};

export const APITest = {
  SHARE_LIST: `shares`,
  SHARES_WRITER: `shares/writer`,
  SHARE_RECOMMENDED: `shares/recommendation`,
  SHARE_MINE: `shares/mine`,
  CHATROOMS: `chatrooms`,
  CHATROOM_MEMBERS: `chatroom-members`,
  CHATS_UNREAD: `chats/unread`,
  CHATROOM_IDS: `chatroom-members`,
  CHAT_UPDATE_READ_TIME: `chat-logs/update-read-time`,
  SOCKET: `socket`,
  LOGIN_FORM: '/login/form',
  LOGIN_VERIFICATION: `login/verification`,
  LOGIN: `login`,
  LOGOUT: `logout`,
  ENTRIES: `entries`,
  CHECK_LOGIN: `reissue/access-token`,
  WISH_LIST: `wish-list`,
  MY_SHARE: `shares/mine`,
  MEMBERS: `members`,
  KEYWORD: `keywords`,
  WEBSOCKET: `websocket`,
  REGISTERED_KEYWORD: `keywords/location`,
  DELETE_REGISTERED_KEYWORD: (id: number) => `keywords/${id}`,
  NOTICE: `notifications`,
  NOTICE_ACTIVITY: `notifications/activity`,
  NOTICE_KEYWORD: `notifications/keyword`,
  DELETE_WISH_LIST: `wish-list`,
  DELETE_HISTORY_LIST: (id: number) => `shares/${id}/entry`,
  DELETE_SALES: (id: number) => `shares/${id}`,
};

export type APITestType = keyof typeof APITest;
