export const API = {
  SHARE_LIST: `/api/shares`,
  SHARES_WRITER: `/api/shares/writer`,
  SHARE_RECOMMENDED: `/api/shares/recommendation`,
  SHARE_MINE: '/api/shares/mine',
  CHATROOMS: '/api/chatrooms',
  CHATROOM_MEMBERS: '/api/chatroom-members',
  CHATS_UNREAD: '/api/chats/unread',
  CHATROOM_IDS: '/api/chatroom-members',
  CHAT_UPDATE_READ_TIME: '/api/chat-logs/update-read-time',
  SOCKET: '/api/socket',
  LOGIN_FORM: '/login/form',
  LOGIN_VERIFICATION: '/api/login/verification',
  LOGIN: '/api/login',
  LOGOUT: '/api/logout',
  ENTRIES: '/api/entries',
  CHECK_LOGIN: '/api/reissue/access-token',
  WISH_LIST: '/api/wish-list',
  MY_SHARE: '/api/shares/mine',
  MEMBERS: '/api/members',
  KEYWORD: '/api/keywords',
  REGISTERED_KEYWORD: '/api/keywords/location',
  DELETE_REGISTERED_KEYWORD: (id: number) => `/api/keywords/${id}`,
  NOTICE: '/api/notifications',
  NOTICE_ACTIVITY: '/api/notifications/activity',
  NOTICE_KEYWORD: '/api/notifications/keyword',
  DELETE_WISH_LIST: '/api/wish-list',
  DELETE_HISTORY_LIST: (id: number) => `/api/shares/${id}/entry`,
  DELETE_SALES: (id: number) => `/api/shares/${id}`,
};
