export const loginMention = '로그인하고 쉐어플레이트를 이용해보세요!';
export const kakaoLoginMention = '카카오로 로그인';
export const noRecentListMention = '최근 검색 기록이 없습니다';
export const inputKeyword = '검색어를 입력하세요';
export const popularKeywordMention = '인기있는 쉐어플레이트';
export const littleDeadlineMention = '시간이 얼마 남지 않았어요!';
export const noLittleTimeListMention = '1시간 이내로 남은\n쉐어 목록이 없습니다.';
export const loginForServiceMention = '로그인을 통해서\n서비스를 이용해주세요';
export const shareDeliveryMention = '함께 음식을 나눠먹어요!';
export const shareIngredientMention = '함께 재료를 나눠보아요!';
export const noRelatedShareList = '관련된 쉐어가 없습니다.';
export const offerShare = '이런 쉐어는 어떠세요?';
export const loginFailedMention = '로그인에 실패했습니다!';
export const searchFailed = '검색 결과가 없습니다.';
export const getChatDdataFailedMention = '채팅을 불러오지 못했습니다!';
export const noRecentChatMention = '(채팅 기록 없음)';
export const notShare = '현재 쉐어 중인 목록이 없습니다.';
export const notExpiry = '현재 만료된 목록이 없습니다.';
export const notReservation = '현재 예약하신 목록이 없습니다.';
export const notWishList = '현재 찜한 리스트가 없습니다.';
export const wrongApproachMEntion = '잘못된 접근입니다!';
export const addKeyword = '알림 키워드 추가해주세요!';
export const searchWayMention = '건물명, 도로명 또는 지번으로 검색';
export const searchAroundMention = '현재 위치로 주소 찾기';
export const checkAddressWithMap = '지도에서 위치 확인하기';
export const noAddressListMention = '검색 결과가 없습니다.\n지번, 도로명, 건물명을 입력해주세요.';
export const addressKeywordQuestionMention = '주소 키워드를\n삭제하시겠습니까?';
export const newShareEnrolledMention = '새로운 쉐어가 등록되었습니다.';
export const failtoGetNoticeMention = '알림 목록을 불러오지 못했습니다.';
export const dataFailed = '데이터를 넣어주세요';
export const fileFailed = '이미지는 최대 5장까지 첨부할 수 있어요';
export const inputValueFailed = '키워드를 입력해주세요';
export const keywordLengthFailed = '키워드는 최대 10개까지 첨부할 수 있어요';
export const failLoadingChatroomsMention = '채팅을 불러오지 못했습니다';
export const historyDeleteMention = '해당 쉐어목록을\n삭제하시겠습니까?';
export const tagInputPlaceholderMention = '#태그를 입력해주세요. (최대 5개)';
export const deleteChatMention =
  '채팅방에서 나가시겠습니까?\n채팅방을 나가면 대화 내용이 삭제됩니다.';
export const exitMention = '네, 나갈래요.';
export const deadlineMention = '등록하신 상품의 시간이 끝나가요!';
export const thirtyMinuitesLeftMention = '상품이 30분 남았습니다!';
export const entryJoinedMention = '쉐어가 신청되었습니다.';
export const entryCanceledMention = '쉐어 신청이 취소되었습니다.';
export const shareCanceledMention = '쉐어가 취소되었습니다.';
export const noRecentNoticeMention = '새로운 알림이 없습니다.';
export const newQuestionChatroomMention = '새로운 문의가 들어왔습니다.';
export const failedToDeleteShareMention = '쉐어를 삭제하지 못했습니다.';
export const successToDeleteShareMention = '쉐어를 성공적으로 삭제했습니다.';
export const questionDeleteShareMention = '해당 쉐어를 삭제하시겠습니까?';
export const questionChatroomMention = (option: string | undefined) =>
  `${option}님이 문의를 남겼습니다.`;
export const entryMention = (name?: string) => `${name}님이 쉐어 신청하였습니다.`;
export const shareCancelMention = (name?: string) => `${name}님이 쉐어를 취소하였습니다.`;
export const entryCancelMention = (name?: string) => `${name}님이 쉐어 신청을 취소하였습니다.`;
export const noticeDeletedMention = (count: number) => `${count}개의 알림이 삭제되었습니다.`;
