export const pathName = {
  main: '/',
  shareList: '/share-list',
  loginCallback: '/login-callback',
  shareDetail: '/share-detail',
  notice: '/notice',
  error: '/error',
  searchShare: '/search-share',
  shareMap: '/shareMap',
  chatrooms: '/chatrooms',
  chatroomDetail: '/chatroom-detail',
  shareForm: '/share-registration',
  shareFormDelivery: '/share-registration/delivery',
  shareFormIngredient: '/share-registration/ingredient',
  profile: '/profile',
  settingsProfile: '/profile/setting',
  editUserInfo: '/profile/setting/edit-user-info',
  salesHistory: '/profile/sales-history',
  purchaseHistory: '/profile/purchase-history',
  wishList: '/profile/wish-list',
  keyword: '/profile/keyword',
  addKeyword: '/profile/keyword/add-keyword',
  other: '/*',
};

export type pathNameKeysType = keyof typeof pathName;
